import { Router, type IRouter } from "express";
import healthRouter from "./health";
import coursesRouter from "./courses";
import studentsRouter from "./students";
import feeStructuresRouter from "./fee-structures";
import vouchersRouter from "./vouchers";
import receiptsRouter from "./receipts";
import reportsRouter from "./reports";
import instructorsRouter from "./instructors";
import authRouter from "./auth";
import budgetRouter from "./budget";
import certificatesRouter from "./certificates";
import classesRouter from "./classes";
import attendanceRouter from "./attendance";
import systemLogsRouter from "./system-logs";
import interneesRouter from "./internees";
import interneeAttendanceRouter from "./internee-attendance";
import dailyReportsRouter from "./daily-reports";
import tasksRouter from "./tasks";
import projectsRouter from "./projects";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(coursesRouter);
router.use(studentsRouter);
router.use(feeStructuresRouter);
router.use(vouchersRouter);
router.use(receiptsRouter);
router.use(reportsRouter);
router.use(instructorsRouter);
router.use(budgetRouter);
router.use(certificatesRouter);
router.use(classesRouter);
router.use(attendanceRouter);
router.use(systemLogsRouter);
router.use(interneesRouter);
router.use(interneeAttendanceRouter);
router.use(dailyReportsRouter);
router.use(tasksRouter);
router.use(projectsRouter);

export default router;
